export interface UserRepresentation_I {
    self: any,
    id: any,
    origin: any,
    createdTimestamp: any,
    username: any,
    enabled: any,
    totp: any,
    emailVerified: any,
    firstName: any,
    lastName: any,
    email: any,
    federationLink: any,
    serviceAccountClientId: any,
    attributes: any,
    credentials: any,
    disableableCredentialTypes: any,
    requiredActions: any,
    federatedIdentities: any,
    realmRoles: any,
    clientRoles: any,
    clientConsents: any,
    notBefore: any,
}